name: build

on: push

env:
  DOTNET_VERSION: '6.0.401' # The .NET SDK version to use
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:

    #name: build-${{matrix.os}}
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        dotnet-quality: ga
        source-url: https://code.lombra.net/api/packages/Lombra/nuget/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_AUTH_TOKEN}}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Create the package
      run: dotnet pack --configuration Release
      
    - name: Publish the package to GPR
      run: dotnet nuget push bin\Release\*.nupkg
